/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agendacontactos;

import java.awt.Component;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Chaparro
 */
public class NewContactWindow extends javax.swing.JFrame {

    /**
     * Creates new form NewContactWindow
     */
    public NewContactWindow() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void crearLog(String nuevoContacto) {
        try {
            if (new File("log.txt").exists() == false) {
                archivo = new FileWriter(new File("log.txt"), false);
            }
            archivo = new FileWriter(new File("log.txt"), true);
            Calendar fechaActual = Calendar.getInstance();

            archivo.write(("[" + String.valueOf(fechaActual.get(Calendar.DAY_OF_MONTH))
                    + "/" + String.valueOf(fechaActual.get(Calendar.MONTH) + 1)
                    + "/" + String.valueOf(fechaActual.get(Calendar.YEAR))
                    + " - " + String.valueOf(fechaActual.get(Calendar.HOUR_OF_DAY))
                    + ":" + String.valueOf(fechaActual.get(Calendar.MINUTE))
                    + ":" + String.valueOf(fechaActual.get(Calendar.SECOND))) + "]: " + nuevoContacto + "\n");
            archivo.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        introDNI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        introNombre = new javax.swing.JTextField();
        introApe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        introTel = new javax.swing.JTextField();
        introDir = new javax.swing.JTextField();
        addContact = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir nuevo contacto");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendacontactos/graphics/ic_add_circle_black_18dp_2x.png"))); // NOI18N
        jLabel1.setText("Crear nuevo contacto");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel2.setText("*DNI:");

        introDNI.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        introDNI.setToolTipText("DNI del nuevo contacto (Campo obligatorio)");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel3.setText("*Nombre:");

        introNombre.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        introNombre.setToolTipText("Nombre del nuevo contacto (Campo obligatorio)");
        introNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introNombreActionPerformed(evt);
            }
        });

        introApe.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        introApe.setToolTipText("Apellidos del nuevo contacto (Campo Obligatorio)");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel4.setText("*Apellidos:");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel5.setText("Teléfono:");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel6.setText("Dirección:");

        introTel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        introTel.setToolTipText("Teléfono del nuevo contacto");
        introTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introTelActionPerformed(evt);
            }
        });

        introDir.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        introDir.setToolTipText("Dirección del nuevo contacto");
        introDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introDirActionPerformed(evt);
            }
        });

        addContact.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        addContact.setForeground(new java.awt.Color(0, 153, 255));
        addContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendacontactos/graphics/ic_save_black_18dp_1x.png"))); // NOI18N
        addContact.setText("Guardar contacto");
        addContact.setToolTipText("Añadir nuevo contacto");
        addContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContactActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendacontactos/graphics/ic_delete_sweep_black_18dp_1x.png"))); // NOI18N
        jButton1.setToolTipText("Borrar todos los campos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendacontactos/graphics/ic_exit_to_app_black_18dp_1x.png"))); // NOI18N
        jButton2.setToolTipText("Volver al menú principal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel7.setText("(Los campos marcados con * son obligatorios)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(6, 6, 6)))
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(introDNI)
                            .addComponent(introApe)
                            .addComponent(introTel)
                            .addComponent(introDir)
                            .addComponent(introNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7)))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(addContact)
                        .addGap(58, 58, 58)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(19, 19, 19))))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(introDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(introNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(introApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(introTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(introDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(addContact)
                    .addComponent(jButton1))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void introTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introTelActionPerformed

    private void introNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introNombreActionPerformed

    private void introDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introDirActionPerformed

    private void addContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContactActionPerformed
        // TODO add your handling code here:
        cDB = new ContactosDB();
        String dni = introDNI.getText();
        String nombre = introNombre.getText();
        String apellidos = introApe.getText();
        String telefono = introTel.getText();
        String direccion = introDir.getText();

        if (dni.length() != 0 && nombre.length() != 0 && apellidos.length() != 0) {
            cDB.insercion(dni, nombre, apellidos, telefono, direccion);

            String log = "New Contact: " + dni
                    + ", " + nombre
                    + ", " + apellidos
                    + ", " + telefono
                    + ", " + direccion;
            this.crearLog(log);
            
            JOptionPane.showMessageDialog(frame, "Contacto creado y añadido al registro");
        } else {
            JOptionPane.showMessageDialog(frame,"Los campos DNI, Nombre y Apellidos no pueden estar vacíos.", "Rellene los campos obligatorios", HEIGHT);
        }

        //Dejando todos los campos de texto de nuevo vacíos:
        introDNI.setText("");
        introNombre.setText("");
        introApe.setText("");
        introTel.setText("");
        introDir.setText("");

        
    }//GEN-LAST:event_addContactActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        introDNI.setText("");
        introNombre.setText("");
        introApe.setText("");
        introTel.setText("");
        introDir.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewContactWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewContactWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewContactWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewContactWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewContactWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addContact;
    private javax.swing.JTextField introApe;
    private javax.swing.JTextField introDNI;
    private javax.swing.JTextField introDir;
    private javax.swing.JTextField introNombre;
    private javax.swing.JTextField introTel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private ContactosDB cDB;
    private FileWriter archivo;
    private Component frame;
}
