/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agendacontactos;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author Chaparro
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLMainTitle = new javax.swing.JLabel();
        jBAddContact = new javax.swing.JButton();
        jBDeleteContact = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBLog = new javax.swing.JButton();
        jBAbout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contactos - Cristian Chaparro");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLMainTitle.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLMainTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendacontactos/graphics/ic_people_black_18dp_2x.png"))); // NOI18N
        jLMainTitle.setText("AGENDA DE CONTACTOS");

        jBAddContact.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jBAddContact.setForeground(new java.awt.Color(0, 102, 153));
        jBAddContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendacontactos/graphics/ic_add_circle_black_18dp_2x.png"))); // NOI18N
        jBAddContact.setText(" Nuevo contacto");
        jBAddContact.setToolTipText("Añadir un nuevo contacto");
        jBAddContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddContactActionPerformed(evt);
            }
        });

        jBDeleteContact.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jBDeleteContact.setForeground(new java.awt.Color(204, 0, 51));
        jBDeleteContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendacontactos/graphics/ic_delete_black_18dp_2x.png"))); // NOI18N
        jBDeleteContact.setText(" Eliminar contacto");
        jBDeleteContact.setToolTipText("Eliminar un contacto existente");
        jBDeleteContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteContactActionPerformed(evt);
            }
        });

        jBModificar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jBModificar.setForeground(new java.awt.Color(0, 102, 153));
        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendacontactos/graphics/ic_create_black_18dp_2x.png"))); // NOI18N
        jBModificar.setText(" Modificar teléfonos");
        jBModificar.setToolTipText("Modificar el teléfono de un contacto existente");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBBuscar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jBBuscar.setForeground(new java.awt.Color(51, 102, 0));
        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendacontactos/graphics/ic_search_black_18dp_2x.png"))); // NOI18N
        jBBuscar.setText(" Buscar");
        jBBuscar.setToolTipText("Buscar un contacto existente por su DNI");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBLog.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jBLog.setForeground(new java.awt.Color(51, 102, 0));
        jBLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendacontactos/graphics/ic_build_black_18dp_1x.png"))); // NOI18N
        jBLog.setText("Log");
        jBLog.setToolTipText("Ventana de registro de altas");
        jBLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLogActionPerformed(evt);
            }
        });

        jBAbout.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jBAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendacontactos/graphics/ic_info_black_18dp_1x.png"))); // NOI18N
        jBAbout.setToolTipText("Acerca de...");
        jBAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAboutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 8)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Ver. Final 1.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBDeleteContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBAddContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBLog)
                                .addGap(18, 18, 18)
                                .addComponent(jBAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLMainTitle)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLMainTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAddContact)
                    .addComponent(jBBuscar))
                .addGap(18, 18, 18)
                .addComponent(jBModificar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBDeleteContact, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBAbout, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBLog, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBDeleteContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteContactActionPerformed
        // TODO add your handling code here:
        v3 = new DeleteContactWindow();
        v3.setVisible(true);
    }//GEN-LAST:event_jBDeleteContactActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        v5 = new BuscarWindow();
        v5.setVisible(true);
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBAddContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddContactActionPerformed
        // TODO add your handling code here:
        v2 = new NewContactWindow();
        v2.setVisible(true);
    }//GEN-LAST:event_jBAddContactActionPerformed

    private void jBLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLogActionPerformed
        // TODO add your handling code here:
        v6 = new LogWindow();
        v6.setVisible(true);
    }//GEN-LAST:event_jBLogActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        // TODO add your handling code here:
        v4 = new ModificarWindow();
        v4.setVisible(true);
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(frame,"Aplicación Creada por Cristian Chaparro Arteaga para el proyecto final del curso de Java de la AEPI \n- Asociación Española de Programadores Informáticos -", "Acerca de...", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jBAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAbout;
    private javax.swing.JButton jBAddContact;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBDeleteContact;
    private javax.swing.JButton jBLog;
    private javax.swing.JButton jBModificar;
    private javax.swing.JLabel jLMainTitle;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private NewContactWindow v2;
    private DeleteContactWindow v3;
    private ModificarWindow v4;
    private BuscarWindow v5;
    private LogWindow v6;
    private Component frame;
}
